# +-------------------------------------------------------------------------+
# | camera.yaml - InfinitySky Camera / General Configuration File           |
# +-------------------------------------------------------------------------+

# Enable system (i.e. taking photos, processing, ...)
enabled: false

# Camera location
location:
  lat: 50.11
  lon: 8.69

# Camera configuration
camera:
  width: 3280
  height: 2464
  rotate: 270
  sharpness: 4.2
  saturation: 1.1
  # Crop the image to these coordinates (px)
  # (count from top left after rotation)
  crop:
    top_left_x: 14
    top_left_y: 475
    bottom_right_x: 2164
    bottom_right_y: 2625
  # Exposure in ms (or auto) and gain (similar to ISO: gain 4 -> ISO 400)
  # Optional offset in minutes to adjust the time. An offset of 20 mins at twilight
  # would move the twilight begin at sunrise 20 mins earlier, at sunset 20 mins later
  # Separate for each mode: day, twilight, night
  capture:
    day:
      exposure: auto
      gain: 1
      offset: 0
    twilight:
      exposure: auto
      gain: 4
      offset: 20
    night:
      exposure: 6000
      gain: 5

# Timelapse configuration
timelapse:
  framerate: 24
  width: 1080
  height: 1080

# Keogram configuration
keogram:
  slice_width: 4
  slice_height: 800
