# +-------------------------------------------------------------------------+
# | camera.yaml - InfinitySky Camera / General Configuration File           |
# +-------------------------------------------------------------------------+

# Enable system (i.e. taking photos, processing, ...)
enabled: false

# Camera location
location:
  lat: 50.11
  lon: 8.69

# Camera configuration
camera:
  width: 3280
  height: 2464
  rotate: 270
  sharpness: 4.2
  saturation: 1.1
  # Crop the image to these coordinates
  # (top left X, top left Y, bottom right X, bottom right Y)
  crop:
    top_left_x: 414
    top_left_y: 430
    bottom_right_x: 2414
    bottom_right_y: 2430
  # Exposure in ms (or auto) and gain (similar to ISO: gain 4 -> ISO 400)
  # Separate for each mode: day, twilight, night
  capture:
    day:
      exposure: auto
      gain: 1
    twilight:
      exposure: auto
      gain: 2
    night:
      exposure: 6000
      gain: 5

# Timelapse configuration
timelapse:
  framerate: 25
  width: 1080
  height: 1080

# Keogram configuration
keogram:
  slice_width: 4
  slice_height: 900
