# +-------------------------------------------------------------------------+
# | user.yaml - User specific configuration of UI and more                  |
# +-------------------------------------------------------------------------+

general:
  # Header
  # Logo file (relative from $base/assets/images)
  logo_file: icons/icon_128.png
  title: InfinitySky
  # Display those in footer
  display_infinitysky_version: true
  display_php_version: true
  display_footer_links: true

# Today area
today:
  show_cam_status: true

# Archive area
archive:
  # Thumbnail to show in overview
  # The first existing file in this list will be used as the thumbnail
  # Time in HH-MM structure
  thumbnail:
    - 12-00
    - 16-00
    - 18-00
    - 20-00
    - 09-00
  # Timelapse video appearance
  video_loop: true
  video_autoplay: true
  # The height of the keogram displayed in the day details
  keogram_height: 500px

# Clean up
cleanup:
  # All values are amount of days, so 60 = 60 days
  # Keep all photos this long
  # Only single photos of each 15 minutes will be kept after that
  keep_full_archive: 14
  # Reduce the archived photos to hourly only (so minute 0) after that
  # Must be higher than keep_full_archive
  keep_reduced_archive: 28
  # Keep keogram slices (where keograms are built from)
  keep_keogram_slices: 7
  # Keep keogram images
  keep_keogram: 90
  # Keep timelapse videos
  keep_timelapse: 90
  # Keep days (archived photos only)
  # Tip: If you want a long term archive, simply adjust
  # or copy data dir to other instance with more space
  keep_whole_day: 90
