# +-------------------------------------------------------------------------+
# | user.yaml - User specific configuration of UI and more                  |
# +-------------------------------------------------------------------------+

general:
  # Header
  # Logo file (relative from $base/assets/images)
  logo_file: icons/icon_128.png
  title: InfinitySky
  # Display those in footer
  display_infinitysky_version: true
  display_php_version: true
  display_footer_links: true

# Today area
today:
  show_cam_status: true

# Archive area
archive:
  # Thumbnail to show in overview
  # The first existing file in this list will be used as the thumbnail
  # Time in HH-MM structure
  thumbnail:
    - 12-00
    - 16-00
    - 18-00
    - 20-00
    - 09-00
  # Timelapse video appearance
  video_loop: true
  video_autoplay: true
  # The height of the keogram displayed in the day details
  keogram_height: 500px
